-- MySQL Script generated by MySQL Workbench
-- qua 16 abr 2025 08:15:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbearia` DEFAULT CHARACTER SET utf8mb4 ;
USE `barbearia` ;

-- -----------------------------------------------------
-- Table `barbearia`.`barbeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiro` (
  `id_barbeiro` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_barbeiro`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamento` (
  `id_agendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATETIME NULL DEFAULT NULL,
  `status` ENUM('pendente', 'confirmado', 'cancelado') NULL DEFAULT 'pendente',
  `barbeiro_id_barbeiro` INT(11) NOT NULL,
  `cliente_id_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`id_agendamento`, `barbeiro_id_barbeiro`, `cliente_id_cliente`),
  INDEX `fk_agendamento_barbeiro1_idx` (`barbeiro_id_barbeiro` ASC) VISIBLE,
  INDEX `fk_agendamento_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_barbeiro1`
    FOREIGN KEY (`barbeiro_id_barbeiro`)
    REFERENCES `barbearia`.`barbeiro` (`id_barbeiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `barbearia`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`servico` (
  `id_servico` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tempo_estimado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `estrela` INT(1) NULL,
  `comentario` VARCHAR(256) NULL,
  `barbeiro_id_barbeiro` INT(11) NOT NULL,
  `servico_id_servico` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`, `barbeiro_id_barbeiro`, `servico_id_servico`),
  INDEX `fk_avaliacao_barbeiro1_idx` (`barbeiro_id_barbeiro` ASC) VISIBLE,
  INDEX `fk_avaliacao_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_barbeiro1`
    FOREIGN KEY (`barbeiro_id_barbeiro`)
    REFERENCES `barbearia`.`barbeiro` (`id_barbeiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `barbearia`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamento_has_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamento_has_servico` (
  `agendamento_id_agendamento` INT(11) NOT NULL,
  `servico_id_servico` INT(11) NOT NULL,
  PRIMARY KEY (`agendamento_id_agendamento`, `servico_id_servico`),
  INDEX `fk_agendamento_has_servico_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_agendamento_has_servico_agendamento1_idx` (`agendamento_id_agendamento` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_has_servico_agendamento1`
    FOREIGN KEY (`agendamento_id_agendamento`)
    REFERENCES `barbearia`.`agendamento` (`id_agendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_has_servico_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `barbearia`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- Inserindo barbeiros
INSERT INTO barbeiro (nome, email, telefone, cpf, data_nascimento, data_admissao)
VALUES 
('João Silva', 'joao@barbearia.com', '11999999999', '12345678901', '1990-01-10', '2023-05-01'),
('Carlos Mendes', 'carlos@barbearia.com', '11988888888', '23456789012', '1988-07-15', '2022-03-10');

-- Inserindo clientes
INSERT INTO cliente (nome, email, telefone, endereco, data_nascimento)
VALUES 
('Pedro Lima', 'pedro@gmail.com', '11977777777', 'Rua das Flores, 123', '1995-03-20'),
('Ana Souza', 'ana@gmail.com', '11966666666', 'Avenida Brasil, 456', '2000-09-30');

-- Inserindo serviços
INSERT INTO servico (nome_servico, descricao, preco, tempo_estimado)
VALUES 
('Corte Masculino', 'Corte de cabelo tradicional', 30.00, 30),
('Barba', 'Design de barba com navalha', 25.00, 20),
('Corte + Barba', 'Combo de corte e barba', 50.00, 50);

-- Inserindo agendamentos
INSERT INTO agendamento (data_agendamento, status, barbeiro_id_barbeiro, cliente_id_cliente)
VALUES 
('2025-04-25 10:00:00', 'confirmado', 1, 1),
('2025-04-25 11:00:00', 'pendente', 2, 2);

-- Inserindo avaliações
INSERT INTO avaliacao (estrela, comentario, barbeiro_id_barbeiro, servico_id_servico)
VALUES 
(5, 'Excelente corte!', 1, 1),
(4, 'Bom atendimento, mas atrasou um pouco.', 2, 2);

-- Inserindo serviços agendados
INSERT INTO agendamento_has_servico (agendamento_id_agendamento, servico_id_servico)
VALUES 
(1, 1),
(1, 2),
(2, 3);
