-- MySQL Script generated by MySQL Workbench
-- qua 16 abr 2025 08:15:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbearia` DEFAULT CHARACTER SET utf8mb4 ;
USE `barbearia` ;

-- -----------------------------------------------------
-- Table `barbearia`.`barbeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiro` (
  `id_barbeiro` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_barbeiro`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamento` (
  `id_agendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATETIME NULL DEFAULT NULL,
  `status` ENUM('pendente', 'confirmado', 'cancelado') NULL DEFAULT 'pendente',
  `barbeiro_id_barbeiro` INT(11) NOT NULL,
  `cliente_id_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`id_agendamento`, `barbeiro_id_barbeiro`, `cliente_id_cliente`),
  INDEX `fk_agendamento_barbeiro1_idx` (`barbeiro_id_barbeiro` ASC) VISIBLE,
  INDEX `fk_agendamento_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_barbeiro1`
    FOREIGN KEY (`barbeiro_id_barbeiro`)
    REFERENCES `barbearia`.`barbeiro` (`id_barbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `barbearia`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`servico` (
  `id_servico` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tempo_estimado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `estrela` INT(1) NULL,
  `comentario` VARCHAR(256) NULL,
  `barbeiro_id_barbeiro` INT(11) NOT NULL,
  `servico_id_servico` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`, `barbeiro_id_barbeiro`, `servico_id_servico`),
  INDEX `fk_avaliacao_barbeiro1_idx` (`barbeiro_id_barbeiro` ASC) VISIBLE,
  INDEX `fk_avaliacao_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_barbeiro1`
    FOREIGN KEY (`barbeiro_id_barbeiro`)
    REFERENCES `barbearia`.`barbeiro` (`id_barbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `barbearia`.`servico` (`id_servico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamento_has_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamento_has_servico` (
  `agendamento_id_agendamento` INT(11) NOT NULL,
  `servico_id_servico` INT(11) NOT NULL,
  PRIMARY KEY (`agendamento_id_agendamento`, `servico_id_servico`),
  INDEX `fk_agendamento_has_servico_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_agendamento_has_servico_agendamento1_idx` (`agendamento_id_agendamento` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_has_servico_agendamento1`
    FOREIGN KEY (`agendamento_id_agendamento`)
    REFERENCES `barbearia`.`agendamento` (`id_agendamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_has_servico_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `barbearia`.`servico` (`id_servico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO barbeiro (nome, email, telefone, cpf, data_nascimento, data_admissao)
VALUES
('André Barbosa', 'andre.barbosa@barbearia.com', '11988887777', '12345678901', '1985-04-15', '2020-01-10'),
('Rogério Lima', 'rogerio.lima@barbearia.com', '11977776666', '23456789012', '1990-09-22', '2021-03-12'),
('Felipe Castro', 'felipe.castro@barbearia.com', '11966665555', '34567890123', '1987-12-01', '2019-07-08');
INSERT INTO cliente (nome, email, telefone, endereco, data_nascimento)
VALUES
('João Mendes', 'joao.mendes@gmail.com', '11950000001', 'Rua Alfa, 10', '1993-01-15'),
('Luana Ribeiro', 'luana.ribeiro@gmail.com', '11950000002', 'Rua Beta, 22', '1995-06-30'),
('Carlos Silva', 'carlos.silva@gmail.com', '11950000003', 'Rua Gama, 35', '1988-10-05');
INSERT INTO servico (nome_servico, descricao, preco, tempo_estimado)
VALUES
('Corte social', 'Corte clássico e elegante', 35.00, 30),
('Barba completa', 'Aparar, desenhar e hidratar a barba', 25.00, 20),
('Massagem capilar', 'Relaxamento com óleo essencial', 45.00, 25);
INSERT INTO agendamento (data_agendamento, status, barbeiro_id_barbeiro, cliente_id_cliente)
VALUES
('2025-05-10 09:00:00', 'confirmado', 1, 1),
('2025-05-10 10:00:00', 'pendente', 2, 2),
('2025-05-10 11:00:00', 'confirmado', 3, 3);
INSERT INTO avaliacao (estrela, comentario, barbeiro_id_barbeiro, servico_id_servico)
VALUES
(5, 'Excelente corte e atendimento!', 1, 1),
(4, 'Barba ficou ótima, voltarei!', 2, 2),
(3, 'Massagem relaxante, mas podia durar mais.', 3, 3);
INSERT INTO agendamento_has_servico (agendamento_id_agendamento, servico_id_servico)
VALUES
(1, 1),  -- Corte social no agendamento 1
(2, 2),  -- Barba completa no agendamento 2
(3, 3);  -- Massagem capilar no agendamento 3
