version: '3.8'

services:
  php:
    build: .
    container_name: "apache_php"
    image: php:8.1.16-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "83:80"

  db:
    image: mariadb:10.5
    container_name: "mariadb-server"
    restart: always
    volumes: 
      - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
      - ./db/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - "3307:3306"
