-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 13:53:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbearia` DEFAULT CHARACTER SET utf8mb4 ;
USE `barbearia` ;

-- -----------------------------------------------------
-- Table `barbearia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`barbeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiro` (
  `id_barbeiro` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`id_barbeiro`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  INDEX `fk_barbeiro_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_barbeiro_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `barbearia`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
,DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `barbearia`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamento` (
  `id_agendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATETIME NULL DEFAULT NULL,
  `status` ENUM('pendente', 'confirmado', 'cancelado') NULL DEFAULT 'pendente',
  `cliente_id_cliente` INT(11) NOT NULL,
  `barbeiro_id_barbeiro` INT(11) NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `fk_agendamento_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_agendamento_barbeiro1_idx` (`barbeiro_id_barbeiro` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_barbeiro1`
    FOREIGN KEY (`barbeiro_id_barbeiro`)
    REFERENCES `barbearia`.`barbeiro` (`id_barbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `barbearia`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
,DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`servico` (
  `id_servico` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tempo_estimado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`agenda_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agenda_servico` (
  `agendamento_id_agendamento` INT(11) NOT NULL,
  `servico_id_servico` INT(11) NOT NULL,
  PRIMARY KEY (`agendamento_id_agendamento`, `servico_id_servico`),
  INDEX `fk_agendamento_has_servico_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_agendamento_has_servico_agendamento1_idx` (`agendamento_id_agendamento` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_has_servico_agendamento1`
    FOREIGN KEY (`agendamento_id_agendamento`)
    REFERENCES `barbearia`.`agendamento` (`id_agendamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_has_servico_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `barbearia`.`servico` (`id_servico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barbearia`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`avaliacao` (
  `idavaliacao` INT(11) NOT NULL AUTO_INCREMENT,
  `estrela` TINYINT(4) NOT NULL,
  `comentario` VARCHAR(256) NULL DEFAULT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `barbeiro_id_barbeiro` INT(11) NOT NULL,
  `servico_id_servico` INT(11) NOT NULL,
  `cliente_id_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_barbeiro1_idx` (`barbeiro_id_barbeiro` ASC) VISIBLE,
  INDEX `fk_avaliacao_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_avaliacao_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_barbeiro1`
    FOREIGN KEY (`barbeiro_id_barbeiro`)
    REFERENCES `barbearia`.`barbeiro` (`id_barbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `barbearia`.`servico` (`id_servico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `barbearia`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


